uint16 idx # the index of the data point
float32 Est_x       # Estimated x poistion by floaty estimator
float32 Est_y       # Estimated y poistion by floaty estimator
float32 Est_z       # Estimated z poistion by floaty estimator
float32 Est_vx      # Estimated x velocity by floaty estimator
float32 Est_vy      # Estimated y velocity by floaty estimator
float32 Est_vz      # Estimated z velocity by floaty estimator
float32 Est_roll        # Estimated roll angle by floaty estimator
float32 Est_pitch       # Estimated pitch angle by floaty estimator
float32 Est_yaw         # Estimated yaw angle by floaty estimator
float32 Est_roll_rate        # Estimated roll rate by floaty estimator
float32 Est_pitch_rate       # Estimated pitch rate by floaty estimator
float32 Est_yaw_rate         # Estimated yaw rate by floaty estimator

float32 Est_f1        # Estimated flap 1 angle by floaty estimator
float32 Est_f2        # Estimated flap 2 angle by floaty estimator
float32 Est_f3        # Estimated flap 3 angle by floaty estimator
float32 Est_f4        # Estimated flap 4 angle by floaty estimator

float32 gyro_x        # Average Gyro info x axis
float32 gyro_y        # Average Gyro info y axis
float32 gyro_z        # Average Gyro info z axis

float32 Control_f1        # Floaty control for flap 1
float32 Control_f2        # Floaty control for flap 2
float32 Control_f3        # Floaty control for flap 3
float32 Control_f4        # Floaty control for flap 4

float32 Command_m1        # The command that flap 1 gets
float32 Command_m2        # The command that flap 2 gets
float32 Command_m3        # The command that flap 3 gets
float32 Command_m4        # The command that flap 4 gets

float32 Opt_x       # Optitrack x poistion
float32 Opt_y       # Optitrack y poistion
float32 Opt_z       # Optitrack z poistion
float32 Opt_roll        # Optitrack roll angle
float32 Opt_pitch       # Optitrack pitch angle
float32 Opt_yaw         # Optitrack yaw angle
